## zinit setup
ZINIT_HOME="$XDG_DATA_HOME/zsh/zinit"
if [ ! -d "$ZINIT_HOME" ]
then
    echo "ZINIT not found. Cloning..."
    git clone --depth 1 https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "$ZINIT_HOME/zinit.zsh"
alias use='zinit light'
alias snip='zinit snippet'
alias ice='zinit ice'
alias load='zinit load'

ice depth"1"
use zsh-users/zsh-completions

autoload compinit
compinit

use hlissner/zsh-autopair
use zdharma-continuum/fast-syntax-highlighting
use MichaelAquilina/zsh-you-should-use
use zsh-users/zsh-autosuggestions
use Aloxaf/fzf-tab

# FZF tab is better. Fight me.
# use marlonrichert/zsh-autocomplete

ice wait'3' lucid
load zsh-users/zsh-history-substring-search

ice wait'2' lucid
load zdharma-continuum/history-search-multi-word

# ice wait'5' lucid
# snip https://gist.githubusercontent.com/hightemp/5071909/raw/
unalias use snip ice load

## oh-my-zsh setup
OMZ_HOME="$HOME/.oh-my-zsh"
if [ ! -d "$OMZ_HOME" ]
then
    echo "OH-MY-ZSH not found. Cloning..."
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo "
# This file was created by the dotfiles sourced zshrc by adityastomar67.
# Do not edit this file directly. Instead, edit the dotfiles zshrc file.
# ~/zsh/.zshrc
if [ -r ~/zsh/.zshrc ]; then
    source ~/zsh/.zshrc
fi
    " > .zshrc
fi

plugins=(
  z
  git
  history
  web-search
  copybuffer
  dirhistory
)
source "$OMZ_HOME/oh-my-zsh.sh"
