#!/bin/bash
# Script to Download my Updated Wallpapers from Github
mkdir -p $HOME/.config/wall/Wallpapers
[ -d "$HOME/.config/wall/Wallpapers" ] && rm -rf ~/.config/wall/Wallpapers

cd ~/.config/wall/
if [ -f 'wall1.jpg' ]; then
  command rm wall*
fi

git clone https://github.com/adityastomar67/Wallpapers 
mv ~/.config/wall/Wallpapers/wall* .
rm -rf ~/.config/wall/Wallpapers
ls | grep "wall[0-9]*.png" > list.txt

list="./list.txt"
while IFS= read -r file ; do
  mv -- "$file" "${file%.png}.jpg"
done < "$list"

command rm list.txt
# ~/.fehbg_
~/.wallpy
